### ISSUE TITLE
OIDC login failing with `missing_client_id`

### ISSUE THREAD

**Issue by amit-yp** [jenkinsci/oic-auth-plugin#179]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  jenkins helm chart version: 4.2.15
  oic-auth:2.3
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

- jenkins deployed in kubernetes using helm chart
- configmap.yaml
```
  jcasc-default-config.yaml: |-
    jenkins:
      authorizationStrategy:
        loggedInUsersCanDoAnything:
          allowAnonymousRead: false
      securityRealm:
        oic:
          clientId: "some-secret"
          clientSecret: "some-secret"
          wellKnownOpenIDConfigurationUrl: "some-secret"
          userInfoServerUrl: "https://some-secret/oauth2/userinfo"
          groupsFieldName: "roles"
          disableSslVerification: true
          escapeHatchEnabled: false
          logoutFromOpenidProvider: true
          emailFieldName: "email"
          userNameField: "email"
          rootURLFromRequest: true
          tokenServerUrl: "https://some-secret/oauth2/token"
          authorizationServerUrl: "https://some-secret/oauth2/authorize?client_id=some-secret&response_type=code&redirect_uri=https%3A%2F%2Fsome-secret%2FsecurityRealm%2FfinishLogin"
          scopes: "openid email profile offline_access"
```

### Reproduction steps

```
jenkins-0 jenkins 2022-11-30 14:40:17.941+0000 [id=12]  WARNING h.i.i.InstallUncaughtExceptionHandler#handleException: Caught unhandled exception with ID fd9aea05-554e-41b2-b7a8-54e09fb573f0                   
jenkins-0 jenkins com.google.api.client.auth.oauth2.TokenResponseException: 400                                                                                                                                  
jenkins-0 jenkins POST https://some-secret/oauth2/token                                                                                                                                                      
jenkins-0 jenkins {                                                                                                                                                                                              
jenkins-0 jenkins   "error" : "invalid_request",                                                                                                                                                                 
jenkins-0 jenkins   "error_description" : "The request is missing a required parameter: client_id",                                                                                                              
jenkins-0 jenkins   "error_reason" : "missing_client_id"                                                                                                                                                         
jenkins-0 jenkins }                                                                                                                                                                                              
jenkins-0 jenkins       at com.google.api.client.auth.oauth2.TokenResponseException.from(TokenResponseException.java:103)                                                                                        
jenkins-0 jenkins       at com.google.api.client.auth.oauth2.TokenRequest.executeUnparsed(TokenRequest.java:308)                                                                                                 
jenkins-0 jenkins       at com.google.api.client.auth.openidconnect.IdTokenResponse.execute(IdTokenResponse.java:115)                                                                                            
jenkins-0 jenkins       at org.jenkinsci.plugins.oic.OicSecurityRealm$3.onSuccess(OicSecurityRealm.java:442)                                                                                                     
jenkins-0 jenkins       at org.jenkinsci.plugins.oic.OicSession.doFinishLogin(OicSession.java:112)                                                                                                               
jenkins-0 jenkins       at org.jenkinsci.plugins.oic.OicSecurityRealm.doFinishLogin(OicSecurityRealm.java:697)                                                                                                   
jenkins-0 jenkins       at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:710)                                                                                                    
jenkins-0 jenkins       at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:397)                                                                                                                 
jenkins-0 jenkins       at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:409)                                                                                                               
jenkins-0 jenkins       at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:207)                                                                                                                         
jenkins-0 jenkins       at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:140)                                                                                                         
jenkins-0 jenkins       at org.kohsuke.stapler.MetaClass$11.doDispatch(MetaClass.java:558)                                                                                                                       
jenkins-0 jenkins       at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:59)                                                                                                         
jenkins-0 jenkins       at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:762)                                                                                                                               
jenkins-0 jenkins       at org.kohsuke.stapler.Stapler.invoke(Stapler.java:894)                                                                                                                                  
jenkins-0 jenkins       at org.kohsuke.stapler.MetaClass$2.doDispatch(MetaClass.java:224)                                                                    
```

### Expected Results

- OIDC should accept the clientId and client_secret i'm providing

### Actual Results

- failing with the exception shown above
