### ISSUE TITLE
Upgrade from 2.2 to 2.3 breaks SSO - "Invalid scopes"

### ISSUE THREAD

**Issue by fostermi** [jenkinsci/oic-auth-plugin#199]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

 Jenkins 2.375.2
 Docker Server Version: 20.10.22

Jenkins casc config:
   plugins.txt
   ...    
    oic-auth:latest
   ...

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Docker:
Server Version: 20.10.22

### Reproduction steps

1. Either have a functioning Jenkins instance with version 2.2 of the plugin or
2. build new Docker image:

```
FROM jenkins/jenkins:2.375.2-lts
COPY --chown=jenkins:jenkins plugins.txt /usr/share/jenkins/ref/plugins.txt
COPY --chown=jenkins:jenkins jenkins-casc /usr/share/jenkins/ref/jenkins-casc
RUN jenkins-plugin-cli --verbose -f /usr/share/jenkins/ref/plugins.txt
```

plugins.txt
```
# Plugins to install
credentials:latest
configuration-as-code:latest
role-strategy:latest
Parameterized-Remote-Trigger:latest
git:latest
slack:latest
generic-webhook-trigger:latest
workflow-job
workflow-job:latest
ws-cleanup:latest
ssh-agent:latest
oic-auth:latest
```

3. Upgrade the plugin on running Jenkins instance from 2.2 to 2.3
4. or Deploy new image with latest plugin.

OIC config in jenkins.yml file for jenkins-casc:
```
  securityRealm:
    oic:
      wellKnownOpenIDConfigurationUrl: https://keycloak.example.com/auth/realms/lasp/.well-known/openid-configuration
      authorizationServerUrl: https://keycloak.example.com/auth/realms/lasp/protocol/openid-connect/auth
      clientId: jenkins-tools
      clientSecret: "${PROP_OIDC_CLIENT_SECRET}"
      disableSslVerification: true
      emailFieldName: email
      escapeHatchEnabled: false
      fullNameFieldName: name
      groupsFieldName: groups
      logoutFromOpenidProvider: true
      endSessionEndpoint: https://keycloak.example.com/auth/realms/lasp/protocol/openid-connect/logout
      postLogoutRedirectUrl: https://jenkins-tools.example.com
      scopes: openid roles profile groups email
      tokenServerUrl: https://keycloak.example.com/auth/realms/lasp/protocol/openid-connect/token
      userNameField: preferred_username
```

### Expected Results

Upon hitting the url of the Jenkins instance, user is redirected to Keycloak to login. Upon success authentication, user is redirected back to Jenkins man dashboard.

### Actual Results

Upon hitting the url of the Jenkins instance, the following error is immediately displayed without ever redirecting to Keycloak:

```
Error from provider: invalid_request. Details: Invalid scopes: web-origins angular_client_scope address phone openid roles profile offline_access groups microprofile-jwt email
```

### Anything else?

Keycloak version 11.0.2.
